### ISSUE TITLE
Cherry-pick?

### ISSUE THREAD

**Issue by agouaillard** [agouaillard/OBS-studio-webrtc#1]
shall we cherry-pick the only commit on the HEAD of m84v26 that is not in the automated-build branch?

**Comment by agouaillard** [comment]
@Palakis

**Comment by Palakis** [comment]
You mean 0106bd5fd8baf4a64061f216a11d2888f534c732? This one was cherry-picked the other way around, from m84-v26.0-automated-builds to m84-v26.0.

**Comment by agouaillard-cosmo** [comment]
OK, so you confirm that m84-v26.0-automated-builds is "complete" and has all the commits, right?

**Comment by Palakis** [comment]
Yes, `m84-v26.0-automated-builds` is complete has all the commits that make up the last binaries I provided. It's OK to merge in `m84-v26.0`.
